apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app
spec:
  selector:
    matchLabels:
      run: payment-app
  replicas: 1
  template:
    metadata:
      labels:
        run: payment-app
    spec:
      containers:
      - name: payment-app
        image: nickholbrook/gs-accessing-data-mysql:v2
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      tolerations:
      - key: ""
        operator: "Exists"
        effect:
---

---
apiVersion: v1
kind: Service
metadata:
  name: payment-app
  labels:
    run: payment-app
spec:
  ports:
  - port: 8080
  selector:
    run: payment-app